### ISSUE TITLE
Old versions can not be restored from the sidebar because file is locked

### ISSUE THREAD

**Issue by max-nextcloud** [nextcloud/files_lock#123]
How to reproduce:
* open a file (.md or .odt)
* add some content so multiple versions exist
* open the versions tab in the sidebar
* try to restore previous version
* see `Could not restore version`.

The server responds with a 500 with this content
```xml
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>OCP\Lock\ManuallyLockedException</s:exception>
  <s:message>"files/AA.mine/test text/restore file version with lock.md" is locked, existing lock on file: files_lock/bd8abcbd-a01a-40c5-8332-b9c2e5c42cd2</s:message>
</d:error>
```
<details>
<summary>
Trace from the server:
</summary>

```yaml
{
app: webdav,
method: MOVE,
url: /remote.php/dav/versions/<user-id>/16523/1838744392,
message: "files/filename.docx" is locked, existing lock on file: files_lock/15551a66-c88c-49ea-8c3c-e85585df40a3,
exception: {
      Exception: OCP\Lock\ManuallyLockedException
      Message: "files/filename.docx" is locked, existing lock on file: files_lock/15551a66-c88c-49ea-8c3c-e85585df40a3
      Code: 0
      Trace: [ 
           {
               file: /var/www/html/nextcloud/apps/files_lock/lib/Storage/LockWrapper.php
               line: 214
               function: checkPermission
               class: OCA\FilesLock\Storage\LockWrapper"
               type: ->
           },
           {
               file: /var/www/html/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php
               line: 301
               function: fopen
               class: OCA\FilesLock\Storage\LockWrapper"
               type: ->
           },
           {
               file: /var/www/html/nextcloud/apps/files_versions/lib/Storage.php
               line: 442
               function: fopen
               class: OCA\FilesLock\Wrapper\Wrapper"
               type: ->
           },
           {
               file: /var/www/html/nextcloud/apps/files_versions/lib/Storage.php
               line: 401
               function: copyFileContents
               class: OCA\Files_Versions\Storage
               type: ::
           },
    ]
}
```
</details>
